# notes from https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#global-npm-dependencies
FROM node:buster
LABEL maintainer="Sam AY <sam3ay@gmail.com>"

ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG HOME=/home/${USERNAME}

ENV NPM_CONFIG_PREFIX=${HOME}/.npm-global
ENV PATH=$PATH:${NPM_CONFIG_PREFIX}/bin
ENV XDG_CONFIG_HOME=/${HOME}/dotfiles/.config

RUN apt-get update && apt-get install -y \
	autoconf \
	automake \
	build-essential \
	ca-certificates \
	cmake \
	git \
	neovim \
	ninja-build \
	openssl \
	pkg-config \
	python-neovim \
	python3-neovim \
	sudo \
	tk-dev \
	unzip \
	wget \
	&& apt-get autoremove -y \
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/*

# Add sudo support for $USERNAME
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
	&& chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR ${HOME}

# custom bashrc
RUN git clone --recurse-submodules https://github.com/sam3ay/dotfiles.git \
	&&  echo ". /${HOME}/dotfiles/.custom_bashrc" >>~/.bashrc

WORKDIR ${HOME}/app

# install ask-cli and aws-cli
RUN npm install -g ask-cli \
	&& npm install --dev jest \
	&& curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
	&& unzip awscliv2.zip \
	&& ./aws/install \
	&& rm -rf awscliv2.zip aws/

USER $USERNAME

RUN mkdir ${HOME}/.ask \
	&& mkdir ${HOME}/.aws

WORKDIR ${HOME}

ENTRYPOINT ["/bin/bash"]